Repository CS2103-AY1819S1-W16-2/main, pull requests merged in 2018-10, with the labels that each got.

#72 DeveloperGuide.adoc: Update Appendix D, E & F
  docs/DeveloperGuide.adoc
Labels: status.Ready

#91 build.gradle: Updated attributes
  build.gradle
Labels: status.Ready

#94 Manage Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ManageCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ManageCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: status.Ready

#96 Add auto-increment id support for Event.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventId.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/test/data/XmlSerializableAddressBookTest/duplicateEventAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalEventsAddressBook.xml
  src/test/java/seedu/address/storage/XmlAdaptedEventTest.java
Labels: status.Ready

#93 DeveloperGuide.adoc updates for CS2101
  docs/DeveloperGuide.adoc
Labels: status.Ongoing

#97 Placeholder Person
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonId.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: status.Ready

#106 Update Record to use EventId and PersonId
  src/main/java/seedu/address/commons/events/ui/RecordChangeEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ManageCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/event/EventId.java
  src/main/java/seedu/address/model/person/PersonId.java
  src/main/java/seedu/address/model/record/EventId.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/record/VolunteerId.java
  src/main/java/seedu/address/storage/XmlAdaptedRecord.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecordEventPanel.java
  src/main/resources/view/RecordEventPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/record/EventIdTest.java
  src/test/java/seedu/address/model/record/VolunteerIdTest.java
  src/test/java/seedu/address/storage/XmlAdaptedRecordTest.java
  src/test/java/seedu/address/testutil/RecordBuilder.java
  src/test/java/seedu/address/testutil/TypicalRecords.java
Labels: status.Ready

#107 Manage Command Completed
  src/main/java/seedu/address/logic/commands/ManageCommand.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/record/RecordContainsEventIdPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecordEventPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RecordEventPanel.fxml
Labels: status.Ready

#109 Update Introduction for DeveloperGuide.adoc and README.adoc
  README.adoc
  docs/DeveloperGuide.adoc
Labels: status.Ready

#111 AddressBookParser: Added manage command
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High, status.Ready

#119 Update language and captions of current implementation section of undo/redo function in DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
Labels: status.Ready

#121 DeveloperGuide.adoc: Setting Up updates
  docs/DeveloperGuide.adoc
Labels: status.Ready

#120 DeveloperGuide.adoc: Implementation updates
  docs/DeveloperGuide.adoc
  docs/diagrams/Command_Manage_SequenceDiagram.pptx
  docs/diagrams/Command_Switch_SequenceDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/images/Command_Manage_SequenceDiagram.png
  docs/images/Command_Switch_SequenceDiagram.png
Labels: status.Ready

#115 UserGuide.adoc: Updated record management section
  docs/UserGuide.adoc
  docs/images/command_manage.png
  docs/images/command_manage_view.png
  docs/images/command_record_add.png
  docs/images/command_record_edit.png
  docs/images/command_switch_after.png
  docs/images/command_switch_before.png
Labels: status.Ready

#112 UserGuide.adoc: Add details of 'exportcert' command
  docs/UserGuide.adoc
Labels: status.Ready

#122 DeveloperGuide.adoc: Implementation updates
  docs/DeveloperGuide.adoc
Labels: status.Ready

#125 DeveloperGuide.adoc: Add implementation details for exporting volunteer certificate
  docs/DeveloperGuide.adoc
  docs/images/VolunteerCert.png
Labels: status.Ready

#129 UserGuide.adoc: Formatting
  docs/UserGuide.adoc
  docs/images/command_clear_after.png
  docs/images/command_clear_before.png
Labels: status.Ready

#127 README.adoc: Minor Cleanup
  README.adoc
Labels: status.Ready

#128 Clean up language and formatting in DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
Labels: status.Ready

#130 DeveloperGuide.adoc: Update certificate export implementation section
  docs/DeveloperGuide.adoc
Labels: status.Ready

#131 UserGuide.adoc: Update 'exportcert' command section
  docs/UserGuide.adoc
Labels: status.Ready

#124 Update DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
Labels: status.Ready

#92 Update ListView UI in MainWindow.fxml
  src/main/java/seedu/address/ui/ContextIndicator.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/fonts/IBMPlexSans-Regular.ttf
  src/main/resources/fonts/OpenSans-Regular.ttf
  src/main/resources/view/ContextIndicator.fxml
  src/main/resources/view/Custom.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecordEventPanel.fxml
Labels: status.Ready

#137 Record Related Commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecordCommand.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/logic/commands/ManageCommand.java
  src/main/java/seedu/address/logic/parser/AddRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/EditRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserRecordUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/ui/RecordEventPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: status.Ready

#148 Update UI in MainWindow.fxml
  src/main/resources/view/Custom.css
  src/main/resources/view/MainWindow.fxml
Labels: status.Ongoing

#144 Clean Deletion Code
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/model/record/RecordContainsVolunteerIdPredicate.java
Labels: status.Ready

#149 Update version number for release
  src/main/java/seedu/address/MainApp.java
Labels: status.Ready

#151 Add Event Panel UI handling on Select event
  src/main/java/seedu/address/commons/events/ui/JumpToEventListRequestEvent.java
  src/main/java/seedu/address/logic/commands/SelectEventCommand.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/ContextIndicator.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/EventPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VolunteerListPanel.java
  src/main/resources/view/Custom.css
  src/main/resources/view/EventPanel.fxml
  src/main/resources/view/RecordEventPanel.fxml
Labels: status.Ready

#153 Disable horizontal scrolling in ResultDisplay.java
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: status.Ready

#152 RecordEventPanel: Disabled horizontal scrolling
  src/main/java/seedu/address/ui/RecordEventPanel.java
  src/main/resources/view/Custom.css
  src/main/resources/view/RecordEventPanel.fxml
Labels: status.Ready

#157 Fix merge conflict error in DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
Labels: status.Ready

#158 Add tags for Event status in EventCard.java and EventPanel.java
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventPanel.java
  src/main/resources/view/Custom.css
  src/main/resources/view/EventPanel.fxml
Labels: status.Ready

#154 UserGuide.adoc Updates
  docs/UserGuide.adoc
  docs/diagrams/Command_Event_Add.pptx
  docs/diagrams/Command_Event_Update.pptx
  docs/diagrams/Command_Record_Add_VolunteerIndex.pptx
  docs/diagrams/Command_Record_Manage.pptx
  docs/diagrams/Command_Record_Update.pptx
  docs/diagrams/Command_Record_Update_VolunteerIndex.pptx
  docs/diagrams/UiLabelled.pptx
  docs/images/Ui.png
  docs/images/UiLabelled.png
  docs/images/command_add_event_after.png
  docs/images/command_clear_after.png
  docs/images/command_clear_before.png
  docs/images/command_event_add_after1.png
  docs/images/command_event_add_after2.png
  docs/images/command_event_add_before.png
  docs/images/command_event_delete_after.png
  docs/images/command_event_delete_before.png
  docs/images/command_event_edit_after.png
  docs/images/command_event_edit_before.png
  docs/images/command_event_list.png
  docs/images/command_manage_view.png
  docs/images/command_record_add.png
  docs/images/command_record_add_after1.png
  docs/images/command_record_add_after2.png
  docs/images/command_record_add_volunteerIndex.png
  docs/images/command_record_delete.png
  docs/images/command_record_edit.png
  docs/images/command_record_edit_after.png
  docs/images/command_record_edit_volunteerIndex.png
  docs/images/command_record_manage_eventIndex.png
  docs/images/command_switch_after.png
  docs/images/command_switch_before.png
Labels: status.Ready

#163 RepoSense fix - Sharan
  .gitignore
  _reposense/config.json
Labels: status.Ready

#161 `exportcert` command [v1.3]
  build.gradle
  src/main/java/seedu/address/logic/commands/ExportCertCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCertCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCertCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCertCommandParserTest.java
Labels: status.Ready

#168 Update of Volunteer Panel UI
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VolunteerCard.java
  src/main/java/seedu/address/ui/VolunteerPanel.java
  src/main/resources/view/Custom.css
  src/main/resources/view/VolunteerListCard.fxml
  src/main/resources/view/VolunteerPanel.fxml
  src/test/java/guitests/guihandles/VolunteerCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.Ready

#169 Update .gitignore to include Volunteer Certs folder
  .gitignore
Labels: status.Ready

#173 Update UserGuide for volunteer
  docs/UserGuide.adoc
  docs/images/UiLabelled.png
  docs/images/command_clear_before.png
  docs/images/command_switch_before.png
  docs/images/command_volunteer_add_after1.png
  docs/images/command_volunteer_add_after2.png
  docs/images/command_volunteer_add_before.png
  docs/images/command_volunteer_delete_after.png
  docs/images/command_volunteer_delete_before.png
  docs/images/command_volunteer_edit_after.png
  docs/images/command_volunteer_edit_before.png
  docs/images/command_volunteer_list.png
Labels: status.Ready

#162 Update `exportcert` feature details in UserGuide.adoc and README.adoc
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CurrentVolunteerCert.png
  docs/images/FinalVolunteerCert.png
  docs/images/VolunteerCert.png
Labels: status.Ready

#180 UserGuide.adoc: Image updates
  docs/diagrams/Command_Record.pptx
  docs/diagrams/UiLabelled.pptx
  docs/images/UiLabelled.png
  docs/images/command_manage_view.png
  docs/images/command_record_add.png
  docs/images/command_record_add_volunteerIndex.png
  docs/images/command_switch_before.png
Labels: status.Ready

#159 DeveloperGuide.adoc Updates
  docs/DeveloperGuide.adoc
  docs/diagrams/Command_Manage_SequenceDiagram.pptx
  docs/diagrams/Command_Switch_SequenceDiagram.pptx
  docs/images/Command_Manage_SequenceDiagram.png
  docs/images/Command_Switch_SequenceDiagram.png
  docs/images/command_manage_sd.png
  docs/images/command_switch_sd.png
Labels: status.Ready

#178 Export Cert Feature: Update export success message to show actual path and add volunteer ID to export file name
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ExportCertCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCertCommandTest.java
Labels: priority.High, status.Ready
